// <auto-generated />
using System;
using GMT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GMT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── Login ─────────────────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.Login", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CorreoInstitucional")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("correo_institucional");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("password_hash");

                b.Property<string>("Rol")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("rol");

                b.Property<int>("IntentosFallidos")
                    .HasColumnType("integer")
                    .HasColumnName("intentos_fallidos");

                b.Property<DateTime?>("UltimoAcceso")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("ultimo_acceso");

                b.Property<bool>("EsVerificado")
                    .HasColumnType("boolean")
                    .HasColumnName("es_verificado");

                b.Property<string>("TokenVerificacion")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("token_verificacion");

                b.Property<DateTime?>("FechaExpiracionToken")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("fecha_expiracion_token");

                b.HasKey("Id");
                b.HasIndex("CorreoInstitucional").IsUnique();
                b.ToTable("login");
            });

            // ── Alumno ────────────────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.Alumno", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("LoginId")
                    .HasColumnType("integer")
                    .HasColumnName("login_id");

                b.Property<string>("NombreCompleto")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("nombre_completo");

                b.Property<string>("NumeroControl")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("numero_control");

                b.Property<string>("Carrera")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("carrera");

                b.Property<int?>("Semestre")
                    .HasColumnType("integer")
                    .HasColumnName("semestre");

                b.Property<string>("Telefono")
                    .HasMaxLength(15)
                    .HasColumnType("character varying(15)")
                    .HasColumnName("telefono");

                b.Property<string>("FotoPerfilUrl")
                    .HasColumnType("text")
                    .HasColumnName("foto_perfil_url");

                b.Property<bool>("DatosCompletos")
                    .HasColumnType("boolean")
                    .HasColumnName("datos_completos");

                b.HasKey("Id");
                b.HasIndex("LoginId").IsUnique();
                b.HasIndex("NumeroControl").IsUnique();
                b.ToTable("alumnos");
            });

            // ── Empresa ───────────────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.Empresa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int?>("LoginId")
                    .HasColumnType("integer")
                    .HasColumnName("login_id");

                b.Property<string>("NombreEmpresa")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("nombre_empresa");

                b.Property<string>("RazonSocial")
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("razon_social");

                b.Property<string>("RFC")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("character varying(13)")
                    .HasColumnName("rfc");

                b.Property<string>("Sector")
                    .HasMaxLength(80)
                    .HasColumnType("character varying(80)")
                    .HasColumnName("sector");

                b.Property<string>("Giro")
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)")
                    .HasColumnName("giro");

                b.Property<string>("Estado")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("estado");

                b.Property<string>("Ciudad")
                    .HasMaxLength(80)
                    .HasColumnType("character varying(80)")
                    .HasColumnName("ciudad");

                b.Property<string>("Direccion")
                    .HasColumnType("text")
                    .HasColumnName("direccion");

                b.Property<string>("NombreContacto")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("nombre_contacto");

                b.Property<string>("PuestoContacto")
                    .HasMaxLength(80)
                    .HasColumnType("character varying(80)")
                    .HasColumnName("puesto_contacto");

                b.Property<string>("TelefonoContacto")
                    .HasMaxLength(15)
                    .HasColumnType("character varying(15)")
                    .HasColumnName("telefono_contacto");

                b.Property<bool>("EstaVerificado")
                    .HasColumnType("boolean")
                    .HasColumnName("esta_verificado");

                b.Property<DateTimeOffset>("FechaRegistro")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("fecha_registro");

                b.Property<bool>("DatosCompletos")
                    .HasColumnType("boolean")
                    .HasColumnName("datos_completos");

                b.HasKey("Id");
                b.HasIndex("LoginId").IsUnique();
                b.HasIndex("RFC").IsUnique();
                b.ToTable("empresas");
            });

            // ── Convenio ──────────────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.Convenio", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("EmpresaId")
                    .HasColumnType("integer")
                    .HasColumnName("empresa_id");

                b.Property<string>("NumeroConvenio")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("numero_convenio");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("estado");

                b.Property<DateOnly?>("FechaInicio")
                    .HasColumnType("date")
                    .HasColumnName("fecha_inicio");

                b.Property<DateOnly?>("FechaFin")
                    .HasColumnType("date")
                    .HasColumnName("fecha_fin");

                b.Property<string>("ArchivoUrl")
                    .HasColumnType("text")
                    .HasColumnName("archivo_url");

                b.HasKey("Id");
                b.HasIndex("EmpresaId");
                b.ToTable("convenios");
            });

            // ── SolicitudPractica ─────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.SolicitudPractica", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AlumnoId")
                    .HasColumnType("integer")
                    .HasColumnName("alumno_id");

                b.Property<int>("EmpresaId")
                    .HasColumnType("integer")
                    .HasColumnName("empresa_id");

                b.Property<int?>("ConvenioId")
                    .HasColumnType("integer")
                    .HasColumnName("convenio_id");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)")
                    .HasColumnName("estado");

                b.Property<DateTimeOffset>("FechaSolicitud")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("fecha_solicitud");

                b.Property<DateOnly?>("FechaInicio")
                    .HasColumnType("date")
                    .HasColumnName("fecha_inicio");

                b.Property<DateOnly?>("FechaFin")
                    .HasColumnType("date")
                    .HasColumnName("fecha_fin");

                b.Property<string>("Proyecto")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("proyecto");

                b.Property<string>("Area")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("area");

                b.HasKey("Id");
                b.HasIndex("AlumnoId");
                b.HasIndex("EmpresaId");
                b.ToTable("solicitudes_practicas");
            });

            // ── DocumentoAlumno ───────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.DocumentoAlumno", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AlumnoId")
                    .HasColumnType("integer");

                b.Property<string>("NombreArchivo")
                    .IsRequired()
                    .HasMaxLength(260)
                    .HasColumnType("character varying(260)");

                b.Property<string>("S3Key")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)");

                b.Property<long>("TamañoBytes")
                    .HasColumnType("bigint");

                b.Property<string>("TipoDocumento")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<DateTimeOffset>("FechaSubida")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.HasIndex("AlumnoId");
                b.ToTable("DocumentosAlumno");
            });

            // ── RegistroPendiente ─────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.RegistroPendiente", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("DatosJson")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TipoRegistro")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("S3Key")
                    .HasColumnType("text");

                b.HasKey("Id");
                b.ToTable("registros_pendientes");
            });

            // ── Relaciones ────────────────────────────────────────────────────
            modelBuilder.Entity("GMT.Models.Alumno", b =>
            {
                b.HasOne("GMT.Models.Login", "Login")
                    .WithOne("Alumno")
                    .HasForeignKey("GMT.Models.Alumno", "LoginId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Login");
            });

            modelBuilder.Entity("GMT.Models.Empresa", b =>
            {
                b.HasOne("GMT.Models.Login", "Login")
                    .WithOne("Empresa")
                    .HasForeignKey("GMT.Models.Empresa", "LoginId")
                    .OnDelete(DeleteBehavior.Cascade);
                b.Navigation("Login");
            });

            modelBuilder.Entity("GMT.Models.Convenio", b =>
            {
                b.HasOne("GMT.Models.Empresa", "Empresa")
                    .WithMany("Convenios")
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Empresa");
            });

            modelBuilder.Entity("GMT.Models.SolicitudPractica", b =>
            {
                b.HasOne("GMT.Models.Alumno", "Alumno")
                    .WithMany("Solicitudes")
                    .HasForeignKey("AlumnoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GMT.Models.Empresa", "Empresa")
                    .WithMany("Solicitudes")
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("GMT.Models.Convenio", "Convenio")
                    .WithMany("Solicitudes")
                    .HasForeignKey("ConvenioId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Alumno");
                b.Navigation("Empresa");
                b.Navigation("Convenio");
            });

            modelBuilder.Entity("GMT.Models.DocumentoAlumno", b =>
            {
                b.HasOne("GMT.Models.Alumno", "Alumno")
                    .WithMany("Documentos")
                    .HasForeignKey("AlumnoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Alumno");
            });

            modelBuilder.Entity("GMT.Models.Login", b =>
            {
                b.Navigation("Alumno");
                b.Navigation("Empresa");
            });

            modelBuilder.Entity("GMT.Models.Alumno", b =>
            {
                b.Navigation("Documentos");
                b.Navigation("Solicitudes");
            });

            modelBuilder.Entity("GMT.Models.Empresa", b =>
            {
                b.Navigation("Convenios");
                b.Navigation("Solicitudes");
            });

            modelBuilder.Entity("GMT.Models.Convenio", b =>
            {
                b.Navigation("Solicitudes");
            });
#pragma warning restore 612, 618
        }
    }
}
